home:
    path: /
    defaults:
        _controller: legacy
        _script: list.php
        
test:
    path: /test
    defaults:
        _controller: todo_list
        
todo:
    path: /todo/{id}
    defaults:
        _controller: legacy
        _script: todo.php